### ISSUE TITLE
LICENCE needed

### ISSUE THREAD

**Issue by stevieflow** [cooperativesuk/worker-co-op-model-rules-company-limited-by-shares#3]
This repository needs a licence , to ensure others can reuse it

Propose that we use CC BY 4.0 https://creativecommons.org/licenses/by/4.0/

Assigning to @athertonjohn to discuss / decide

**Comment by athertonjohn** [comment]
Ok looks good to me.

**Comment by athertonjohn** [comment]
Now i'm back off holiday, just getting this checked by our legal team first though

**Comment by athertonjohn** [comment]
Head of Advice is happy to confirm use of CC BY 4.0 https://creativecommons.org/licenses/by/4.0/

**Comment by stevieflow** [comment]
@BibianaC @bjwebb - please can you add the LICENCE?

**Comment by BibianaC** [comment]
@stevieflow I have created a PR https://github.com/cooperativesuk/worker-co-op-model-rules-company-limited-by-shares/pull/5

**Comment by ghost** [comment]
Can we close this issue now?

**Comment by BibianaC** [comment]
Yes, thanks @odscjames
