### ISSUE TITLE
Create a tagged version of the rules

### ISSUE THREAD

**Issue by stevieflow** [cooperativesuk/worker-co-op-model-rules-company-limited-by-shares#6]
@athertonjohn if you can confirm that all is OK with the document, we can then create a version 1.0 in GitHub - which will be the version people can fork

@bjwebb - would you agree?

**Comment by athertonjohn** [comment]
Yep fine with me to confirm and yes do show me how to do chages properly
for future ones !

**Comment by Bjwebb** [comment]
When people fork the repo, they fork a branch. If you want you could make a `1.0` branch, and set that as default in the GitHub UI.

You could tag `v1.0.0` if you wanted. This would help record the history of when the first stable release was made.

**Comment by ghost** [comment]
I can pick this up and do a mini tutorial online, or I might be in Manchester soon?
